#!/bin/bash
# See also http://codeimpossible.com/2011/12/16/Stupid-Git-Trick-getting-contributor-stats/
url=$1
dir=$(mktemp -d)
git clone $url $dir 2>/dev/null >/dev/null
cd $dir
git shortlog -s -n | sed 's/^\s\+\([0-9]\+\)\s\+\(.\+\)/"\2":\1/g' | tr "\\n" "," | sed 's/,$/}/g' | sed 's/^/{/g'
